rcfile option

diff --git a/bin/assert b/bin/assert
--- a/bin/assert
+++ b/bin/assert
@@ -1,14 +1,13 @@
 #!/usr/bin/env bash
 
-#assert statement has 0 return status
+# - If fail, print statement to stderr and exit 1
+# - Else exit 0.
 
-#sample calls:
-  #assert true
-  #assert [ 1 = 1 ]
-  #assert [ "a b" = "a b" ]
+# Sample calls:
 
-#if fail, print statement to stderr and exit 1
-#else exit 0
+    #assert true
+    #assert [ 1 = 1 ]
+    #assert [ "a b" = "a b" ]
 
 "$@"
 if [ ! "$?" = 0 ]; then
