rename-basename working

diff --git a/latex-to-pdf b/latex-to-pdf
--- a/latex-to-pdf
+++ b/latex-to-pdf
@@ -4,34 +4,72 @@
 #
 # Ciro D. Santilli 
 #
-# Convenient wrapper for pdflatex
+# Wrapper for pdflatex
 #
-# Takes path without extension of the .tex file
+# Takes tex path with or without extension.
 #
-# Puts all auxiliary files in ./aux folder.
-# The pdf is put on the same folder as the .tex file
+# May put auxiliary and output files in different output directories
+# but always with the same basename-noext
 #
-# Automates bibtex and synctex.
+# The default if to put all in the same directory as the .tex.
+#
+# Also does bibtex and synctex.
 #
 #------------------------------------------------------------
 
 set -u # error on undefined variable
 set -e # stop execution if one command returns error
 
-if [  $# -ne 1 ]
-then
-  echo "Usage: latex-to-pdf tex-path-optext" 1>&2
+usage()
+{
+  echo "Usage: latex-to-pdf " 1>&2
+}
+
+if [ $# -gt 0 ]; then
+  INPUT_PATH_NOEXT="$( basename-noext "$1" )"
+  shift
+else
+  usage
   exit 1
 fi
 
-INPUT_PATH_NOEXT="$( basename-noext "$1" )"
-AUX_DIR="./aux" # where auxiliary files will be put
+# optional positional arguments
+AUX_DIR="./"
+OUT_DIR="./"
+
+if [ $# -gt 0 ]; then
+  AUX_DIR="$1"
+  shift
+fi
+
+if [ $# -gt 0 ]; then
+  OUT_DIR="$1"
+  shift
+fi
+
+echo "$AUX_DIR"
+
+# make auxiliary directory if necessary. abort operation if it is a file.
+if [ ! -d "$AUX_DIR" ]; then
+  if [ ! -e "$AUX_DIR" ]; then
+    mkdir -p "$AUX_DIR"
+  else
+    echo "The auxiliary folder '$AUX_DIR' already exists, and is a file, aborting operation." 1>&2
+    exit 1
+  fi
+fi
 
 # make pdf with bibtex and synctex
 pdflatex -output-directory "$AUX_DIR" "$INPUT_PATH_NOEXT"
-bibtex ./aux/"$INPUT_PATH_NOEXT"
-pdflatex -output-directory "$AUX_DIR" "$INPUT_PATH_NOEXT"
-pdflatex -output-directory "$AUX_DIR" -synctex=1 -interaction=nonstopmode "$INPUT_PATH_NOEXT"
-mv "$AUX_DIR"/"$INPUT_PATH_NOEXT".pdf .
+bibtex "$AUX_DIR"/"$INPUT_PATH_NOEXT"
+pdflatex -interaction=nonstopmode -output-directory "$AUX_DIR" "$INPUT_PATH_NOEXT"
+pdflatex -interaction=nonstopmode -output-directory "$AUX_DIR" -synctex=1 -interaction=nonstopmode "$INPUT_PATH_NOEXT"
+
+# pdf latex puts output and auxiliary files in the same place.
+# this allows to separate them.
+if [ "$AUX_DIR" != "$OUT_DIR"  ]; then
+  OUT_PATH="$AUX_DIR"/"$INPUT_PATH_NOEXT".pdf
+  mv "$OUT_PATH" "$OUT_DIR"
+fi
 
 exit 0
